// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeScript, fs, path;

  fs = require('fs');

  path = require('path');

  CoffeeScript = require('coffee-script');

  module.exports = function(builder) {
    return builder.hook('before scripts', function(pkg) {
      var coffee;
      coffee = pkg.conf.coffee;
      if (!coffee) {
        return;
      }
      return coffee.forEach(function(option) {
        var compiled, destPath, dirname, srcPath, str;
        srcPath = pkg.path(option.src);
        destPath = pkg.path(option.dest);
        if (!fs.existsSync(destPath)) {
          dirname = path.dirname(destPath);
          if (!fs.existsSync(dirname)) {
            fs.mkdirSync(dirname);
          }
        }
        str = fs.readFileSync(srcPath, 'utf8');
        compiled = CoffeeScript.compile(str, {
          bare: true
        });
        return fs.writeFileSync(destPath, compiled, 'utf-8');
      });
    });
  };

}).call(this);
